name: CI Pipeline

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.0.1'

    - name: Change directory to application
      run: cd /codebase/rdicidr-0.1.0

    - name: Install dependencies
      run: npm install
      working-directory: ./codebase/rdicidr-0.1.0

    - name: Run linter
      run: npm run lint
      working-directory: ./codebase/rdicidr-0.1.0

    - name: Run formatter
      run: npm run prettier
      working-directory: ./codebase/rdicidr-0.1.0

    - name: Run tests
      run: CI=true npm run test
      working-directory: ./codebase/rdicidr-0.1.0

    - name: Build application
      run: npm run build
      working-directory: ./codebase/rdicidr-0.1.0